### ISSUE TITLE
Facing build error on celestia-node v0.15.0 go 1.23.0

### ISSUE THREAD

**Issue by upnodedev** [celestiaorg/celestia-node#3694]
### Celestia Node version

v0.15.0

### OS

Ubuntu 22.04.3 LTS

### Install tools

go v1.23.0

### Steps to reproduce it

Build celestia-node v0.15.0 with go v1.23.0 will face error

Note that it's working on go v1.22.6

### Expected result

Build succeed

### Actual result

Build failed with go v1.23.0 and celestia-node v0.15.0

### Relevant log output

```Shell
--> Building Celestia
# github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
make: *** [Makefile:39: build] Error 1
```

**Comment by Wondertan** [comment]
The pyroscope dependency in v0.15.0 doesn't support go1.23, thus the error. To use v0.15.0 you would need to downgrade.
